[tool.mypy]
disable_error_code = ["union-attr", "var-annotated", "import-untyped"]
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = false
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
enable_incomplete_feature = ["Unpack"]
follow_imports_for_stubs = true
ignore_missing_imports = true
namespace_packages = true
no_implicit_optional = true
pretty = true
show_absolute_path = true
show_error_codes = true
show_error_context = true
strict = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.ruff]
ignore = [
  "F403",
  "F405",
  "E501",
  "B008",
  "C901",
  "W191",
  "UP007",
  "UP006",
]
select = [
  "E",
  "W",
  "F",
  "I",
  "C",
  "B",
  "UP",
]
